"""Original virtual recipes and pretend roleplay scenarios."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'assets/content/meadow.json';pack=json.loads(p.read_text())
def step(action,prompt,symbol,options,repeat=1,**extra):return dict(action=action,prompt=prompt,symbol=symbol,options=options,repeat=repeat,**extra)
def recipe(id,title,steps):return dict(id=id,title=title,topic=title.lower(),theme='Nature',steps=steps,subtitle='Cook in our imagination',access='library')
pack['cooking']=[
recipe('pancakes','Cloud-soft pancakes',[
 step('choose','Choose a pretend flour for our bowl.','○',['Oat flour','Wheat flour']),step('pour','Pour our pretend milk into the bowl.','◒',['Pour milk']),step('mix','Swirl the pretend batter three times.','◌',['Mix'],3),step('timing','Watch our imaginary pancake turn golden.','●',['Ready'],seconds=2),step('decorate','Choose a topping for our picture-perfect pancake.','✦',['Berries','Banana stars']),step('serve','Serve our imaginary picnic to Milo.','♥',['Share our pancakes'])]),
recipe('sandwich','A rainbow sandwich',[
 step('choose','Choose bread for our pretend sandwich.','▱',['Triangle bread','Square bread']),step('spread','Swipe or tap to spread our imaginary filling.','▰',['Spread'],2),step('assemble','Add a colourful pretend layer.','▤',['Tomato','Cucumber']),step('assemble','Choose the top of our sandwich.','▱',['A triangle lid','A square lid']),step('serve','Our pretend sandwich is ready to share.','♥',['Serve our sandwich'])]),
recipe('fruit-bowl','A fruit constellation',[
 step('choose','Choose a bowl for our pretend fruit.','◡',['Round bowl','Star bowl']),step('choose','Pick the first imaginary fruit.','●',['Apple moons','Banana stars']),step('assemble','Add another colour to the bowl.','✦',['Berry dots','Melon triangles']),step('mix','Turn the pretend fruit gently, twice.','◌',['Toss gently'],2),step('decorate','Choose a pattern on top.','★',['A circle','A little star']),step('serve','Offer Milo a pretend fruit constellation.','♥',['Share our fruit'])]),
recipe('pizza','A garden pizza',[
 step('choose','Choose a shape for our pretend pizza.','○',['Round','Heart']),step('spread','Spread the imaginary tomato colour.','●',['Spread sauce'],2),step('assemble','Place colourful garden shapes.','▲',['Pepper triangles','Mushroom moons']),step('decorate','Finish with a pattern.','✦',['A spiral','A smiling face']),step('timing','Our magic pretend oven glows softly. No real heat here.','☀',['Ready'],seconds=2),step('serve','Share our imaginary garden pizza.','♥',['Serve our pizza'])]),
recipe('cake','A friendship cake',[
 step('choose','Choose a pretend cake flavour.','○',['Vanilla cloud','Berry dream']),step('pour','Pour the imaginary mixture into our bowl.','◒',['Pour']),step('mix','Mix three friendly circles.','◌',['Mix'],3),step('assemble','Stack two soft pretend cake layers.','▤',['Add a layer'],2),step('spread','Cover the imaginary cake in a colour you like.','▰',['Peach icing','Sky icing']),step('decorate','Add a friendship decoration.','♥',['Hearts','Stars','Flowers']),step('serve','Every friend can imagine a slice.','♥',['Share our cake'])])]
def role(id,title,outfit,topic,rows):return dict(id=id,title=title,topic=topic,outfit=outfit,theme={'astronaut':'Space','doctor':'Animals','detective':'Dinosaurs'}.get(outfit,'Nature'),subtitle='A pretend adventure',access='library',steps=[step(*row) for row in rows])
pack['roleplay']=[
role('astronaut-mission','The tiny moon mission','astronaut','moon rescue',[
 ('choose','Choose our pretend spacecraft.','△',['A moon boat','A star rocket']),('prop','Take a useful imaginary tool.','✦',['A star map','A listening radio']),('choice','A little robot has lost its way. How can we help?','◇',['Ask where it wants to go','Look at the map together']),('assemble','Make a safe pretend landing place.','▤',['Lay down soft moon blocks']),('serve','Welcome our robot friend home.','♥',['Share the moon story'])]),
role('chef-picnic','The chef’s cosy picnic','chef','shared picnic',[
 ('choose','Who shall our pretend picnic welcome?','♥',['Milo and a fox','Milo and a dinosaur']),('prop','Choose a picnic prop.','▤',['A blanket','A basket']),('assemble','Make room for every pretend guest.','○',['Set a place'],3),('choice','One friend likes a different flavour.','✦',['Offer another choice','Ask what they enjoy']),('serve','Invite everyone to our imaginary picnic.','♥',['Welcome, friends!'])]),
role('doctor-toy','A cosy place for Teddy','doctor','caring for a toy',[
 ('choose','We are pretending with toys, not giving real medical advice. Choose a toy friend.','♥',['Teddy','Toy rabbit']),('prop','Which comforting prop shall we bring?','▤',['A little blanket','A story book']),('choice','Our toy would like a quiet moment.','☾',['Listen softly','Sit nearby']),('assemble','Make a cosy pretend resting place.','▱',['Add a cushion','Add a soft blanket']),('serve','Tell our toy it can rest as long as it likes.','♥',['Enjoy your cosy rest'])]),
role('artist-gallery','The gallery of surprises','beret','dream gallery',[
 ('choose','Choose a theme for our imaginary gallery.','✦',['Dream gardens','Funny planets']),('prop','Pick a pretend artist’s tool.','▰',['A wide brush','A tiny brush']),('decorate','Make an imaginary mark. Every mark is welcome.','◌',['A swirl','A zigzag','A dot']),('assemble','Find a place for a friend’s picture too.','▤',['Leave a space on the wall']),('serve','Open our pretend gallery without choosing a winner.','♥',['Everyone’s picture belongs'])]),
role('detective-button','The mystery of the moon button','detective','moon button mystery',[
 ('prop','Take a pretend detective tool.','○',['A magnifying glass','A notebook']),('choice','A moon button is missing from our costume box. Where shall we look?','☾',['Under the pretend rug','Beside the story book']),('prop','We find a thread and a little round mark.','◌',['Look closely']),('choice','How could we find out more without blaming anyone?','✦',['Ask a friendly question','Look for another clue']),('serve','The button was tucked inside the folded scarf. Mystery solved kindly!','♥',['Return the moon button'])]),
role('builder-bridge','A bridge for little feet','builder','welcoming bridge',[
 ('choose','Choose pretend building blocks.','■',['Wooden-looking blocks','Cloud blocks']),('assemble','Place two steady supports.','▤',['Place a support'],2),('assemble','Lay a broad pretend path.','▰',['Add a path piece'],3),('choice','A tiny toy needs smaller steps.','▲',['Add a middle step','Make a gentle slope']),('serve','Invite different pretend friends to cross at their own pace.','♥',['Our bridge welcomes everyone'])])]
pack['version']=5;p.write_text(json.dumps(pack,ensure_ascii=False,indent=2)+'\n')
print('Added 5 recipes and 6 roleplay scenarios')
